# Generated by Django 2.1.3 on 2018-11-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_personaldata_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
